### ISSUE TITLE
Remove dependence on Java

### ISSUE THREAD

**Issue by jar600** [probcomp/metaprob#37]
https://twitter.com/bobfrankston/status/1027210690443010049?s=11

Looks like Oracle will be charging for updates going forward, which I assume includes security updates. This would mean the end of Java as a 'free as in beer' platform, and we are currently depending on that, assuming we want ordinary people to use metaprob eventually.

Maybe there will still be OpenJDK, but I don't know how solid that effort is.

Fortunately there are other Clojure implementations, right?

**Comment by jar398** [comment]
Yes, for as long as Oracle continues to provide them.

@zane and I talked about this. The _old_ risks of using Java remain: Oracle could at any time say it is no longer providing free updates or versions to anyone. (Public promises from companies are absolutely worthless when there is no applicable contract, and Oracle is not bound by its own application of GPL.) At that point we (and our users) would have to rely on OpenJDK, and it's not clear that the OpenJDK developer community (if it exists at all) would be up to the task of maintaining Java. I don't know, maybe they would rally; they seem to have friends in high places.

The _new_ risk is not so much to probcomp directly but to _users_ of metaprob (or any other probcomp clojure application): they could build a system (web app etc.), put it into production, and then find that they can't fix some security vulnerability or other bug given the resources they have, because of incompatibilities between JDK versions. Yes, _probably_ updating to the latest Java version will be pretty easy for them (it usually has been in the past), but there's a chance it won't be.

The increase in risk is not so extreme as I thought, and I should probably close this issue.

**Comment by jar398** [comment]
Some news on this front:

https://blog.joda.org/2018/09/do-not-fall-into-oracles-java-11-trap.html

The implications are sort of complex I think, but basically either
- our users will have to use OpenJDK, not Oracle, OR
- our users will have to qualify as 'development users' and not 'production users' of Oracle JDK, OR
- we will have to determine that Clojure (and hence metaprob) work in the absence of the JDK itself, AND tell people not to download Oracle JDK (just the JRE).

**Comment by zane** [comment]
We can satisfy the spirit of this issue by verifying that Metaprob works on OpenJDK.
