### ISSUE TITLE
Defensive programming around lazy maps is unnecessary

### ISSUE THREAD

**Issue by zane** [probcomp/metaprob#57]
Follow-up work from [this comment](https://github.com/probcomp/metaprob-clojure/pull/46#discussion_r219738642) on #46. 

There are a few places, for example in `state.clj`, where we do some defensive programming around laziness in maps. e.g. for map `m` 
```
(doseq [entry m] true)
```
This is unnecessary as the only place laziness shows up in Clojure is in lazy sequences. We should remove those guards.

**Comment by jar398** [comment]
Remove them only when we know the argument is not a `seq`, right?  I did add them for a reason, once, after tracking down some bug. They were needed at the time but it seems either the code has evolved so that some of them are no longer needed, or I was overzealous. But some may still be needed (I haven't checked) because the delayed code may have side effects that need to happen early, or with the correct dynamic variables in place.

**Comment by zane** [comment]
Yes, that's right.

**Comment by zane** [comment]
Fixed by #123 or earlier.
