### ISSUE TITLE
What's going on with metaprob.examples.all-test?

### ISSUE THREAD

**Issue by zane** [probcomp/metaprob#67]
Right now all it contains is:

```
(defn foo [] 'hello)
```

I'm guessing that the idea was that it would at some point replace `metaprob.examples.main`?

**Comment by jar398** [comment]
Well, as you might expect, there is some history to this, and the explanation is to be found in the history.

I made a version of the `all` module, which essentially does nothing other than a bunch of requires, and one day it failed because there was a mistake in one of these requires.  So, I added a test to force `lein test` to at least try to load the module, so that any errors loading would be flagged.

Since there is no relationship to `main` I don't think there should be any such connection.

As far as I'm concerned the test should stand pretty much as it is since it does exactly what was intended and I can't think of anything else it should do.  If there is to be a change, it would be the addition of a comment explaining this.

`all` is a user interface feature and should not be used for any other purpose than setting up a  REPL for use by people who don't know about, or don't want to be bothered with, using `require` or `use`.  Nobody should ever require (use, etc.) `all`. Because it contains no code, there can be no tests of it other than whether it loads.

**Comment by jar398** [comment]
Also, the reason the `defn foo` is there is that Clojure didn't accept the file if there was nothing there (which is what I wanted to do).

**Comment by zane** [comment]
Instead of adding comment would it be acceptable to replace `(def foo …)` with a test that runs `(require 'metaprob.examples.all)`? It might make the intent clearer.

**Comment by jar398** [comment]
That's a fine idea.
