### ISSUE TITLE
"steady" state implementation should be moved out of the source tree

### ISSUE THREAD

**Issue by zane** [probcomp/metaprob#80]
Per @jar398 in [this comment](https://github.com/probcomp/metaprob-clojure/pull/76#issuecomment-427689189) the "steady" state implementation in `metaprob.state` is vestigial and should be either removed, converted to tests, or converted to documentation.

**Comment by jar398** [comment]
I originally wrote the 'steady' (concise) implementations as comments, and then realized that if they were real code, I could swap out the hairy, error-prone, 'unsteady' implementations just be setting `steady?` to true, and if that caused a broken test to pass, then the error would be localized to the 'unsteady' implementations, which are just optimizations of the 'steady' ones.

Four methods remain that do not have optimized 'unsteady' forms (`set-value`, `clear-value`, `set-subtrace`, `clear-subtrace`). I don't know whether they need them (in order to get the best possible order of growth for recursions that use them) but my feeling is that they probably do. This was work in progress when I left off work on this file.

The 'steady' versions don't have much utility at this point (now that this module works) and I would favor of turn them back into comments, as in:

    (defn value ... 
      ;; This function should return the same value that (get (state-to-map state) :value)  would.
    ...)

I.e. do not factor them out - comment them out.
